/**
 * Design tokens — TypeScript mirror of the Tailwind v4 `@theme` block in
 * `src/styles/globals.css`. Two surfaces, one source of meaning:
 *
 *   - Tailwind utility classes (`bg-background`, `rounded-control`, …) are
 *     generated by the v4 compiler reading `globals.css`. Use these in JSX.
 *   - The `tokens` const below is the same values exposed as a TypeScript
 *     object — for charting libraries, canvas drawing, animation libs, or
 *     anywhere a raw value is needed instead of a class name.
 *
 * If you change a value here, mirror it in `globals.css` (or vice versa).
 * They MUST stay in lockstep — there's a `pretest` check planned to catch
 * drift; for now it's a discipline thing.
 */

export const colors = {
  background: '#f4efe6',
  foreground: '#2f3b34',
  muted: '#ece4d7',
  mutedForeground: '#6c756d',
  border: '#d9ccba',
  accent: '#7b9a86',
  accentForeground: '#f8f5ef',
  success: '#7fa57f',
  destructive: '#c67b63',
} as const;

export const radii = {
  bubble: '22px',
  control: '9999px',
  container: '12px',
} as const;

export const fonts = {
  sans: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, ui-sans-serif, system-ui, sans-serif',
  serif: '"Fraunces", "Iowan Old Style", Georgia, ui-serif, serif',
} as const;

export const tokens = {
  colors,
  radii,
  fonts,
} as const;

export type ColorToken = keyof typeof colors;
export type RadiusToken = keyof typeof radii;
export type FontToken = keyof typeof fonts;
