# State is in GCS. The bucket name is wired in via -backend-config=backend.hcl
# which is generated by infra/bootstrap/bootstrap.sh and gitignored.
terraform {
  required_version = ">= 1.4.0"

  backend "gcs" {}

  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 6.12"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 6.12"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}
